spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}