name: ilcle CI/CD

on:
  push:
    branches: [ "CICD" ]
#  pull_request:
#    branches: [ "main" ]

permissions:
  contents: read
  
env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  PROJECT_NAME: ilcle
    # Database
  DB_URL: ${{ secrets.DB_URL }}
  DB_USERNAME: ${{ secrets.DB_USERNAME }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  
  # JWT Secret
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
        
        
      # 안되면 위에 빌드랑 퍼미션 대신 이거 써보기
#     - name: Grant execute permission for gradlew
#       run: chmod +x ./gradlew
#       shell: bash

#     - name: Build with Gradle
#       run: ./gradlew build
#       shell: bash

        

    - name: Make zip file
      run: zip -r ./$GITHUB_SHA.zip .
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    # S3에 업로드
    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$PROJECT_NAME/
      
    # Deploy
    - name: Deploy
      run: |
        aws deploy create-deployment 
        --application-name cicd 
        --deployment-config-name CodeDeployDefault.AllAtOnce 
        --deployment-group-name cicd-project 
        --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$PROJECT_NAME/$GITHUB_SHA.zip 
        --region ap-northeast-2 
